/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './app/__root'
import { Route as gameIndexRouteImport } from './app/(game)/index'

const gameIndexRoute = gameIndexRouteImport.update({
  id: '/(game)/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof gameIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof gameIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/(game)/': typeof gameIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/'
  fileRoutesByTo: FileRoutesByTo
  to: '/'
  id: '__root__' | '/(game)/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  gameIndexRoute: typeof gameIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/(game)/': {
      id: '/(game)/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof gameIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  gameIndexRoute: gameIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
